spring:
  application:
    name: GOP_server
  datasource:
    url: jdbc:mysql://mariadb:3306/gop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000
      minimum-idle: 2
      max-lifetime: 1800000
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: create
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  security:
    debug: true
  mail:
    host: smtp.naver.com
    port: 465
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            enable: true
server:
  port: 9977
  error:
    whitelabel:
      enabled: false
google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    pw: ${GOOGLE_CLIENT_PW}
    redirect-uri: https://web-gopprj-m128ei6pc6510b38.sel4.cloudtype.app/oauth2/callback
